#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GymPanzee.Controllers
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="GymPanZee")]
	public partial class GympanzeeDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertActivity(Activity instance);
    partial void UpdateActivity(Activity instance);
    partial void DeleteActivity(Activity instance);
    partial void InsertBodyHalf(BodyHalf instance);
    partial void UpdateBodyHalf(BodyHalf instance);
    partial void DeleteBodyHalf(BodyHalf instance);
    partial void InsertExerciseCategory(ExerciseCategory instance);
    partial void UpdateExerciseCategory(ExerciseCategory instance);
    partial void DeleteExerciseCategory(ExerciseCategory instance);
    partial void InsertExerciseEquipmentCategory(ExerciseEquipmentCategory instance);
    partial void UpdateExerciseEquipmentCategory(ExerciseEquipmentCategory instance);
    partial void DeleteExerciseEquipmentCategory(ExerciseEquipmentCategory instance);
    partial void InsertExerciseMachine(ExerciseMachine instance);
    partial void UpdateExerciseMachine(ExerciseMachine instance);
    partial void DeleteExerciseMachine(ExerciseMachine instance);
    partial void InsertFacility(Facility instance);
    partial void UpdateFacility(Facility instance);
    partial void DeleteFacility(Facility instance);
    partial void InsertTargetBodyPart(TargetBodyPart instance);
    partial void UpdateTargetBodyPart(TargetBodyPart instance);
    partial void DeleteTargetBodyPart(TargetBodyPart instance);
    partial void InsertUser(User instance);
    partial void UpdateUser(User instance);
    partial void DeleteUser(User instance);
    #endregion
		
		public GympanzeeDBDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["GymPanZeeConnectionString1"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public GympanzeeDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GympanzeeDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GympanzeeDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GympanzeeDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Activity> Activities
		{
			get
			{
				return this.GetTable<Activity>();
			}
		}
		
		public System.Data.Linq.Table<BodyHalf> BodyHalfs
		{
			get
			{
				return this.GetTable<BodyHalf>();
			}
		}
		
		public System.Data.Linq.Table<ExerciseCategory> ExerciseCategories
		{
			get
			{
				return this.GetTable<ExerciseCategory>();
			}
		}
		
		public System.Data.Linq.Table<ExerciseEquipmentCategory> ExerciseEquipmentCategories
		{
			get
			{
				return this.GetTable<ExerciseEquipmentCategory>();
			}
		}
		
		public System.Data.Linq.Table<ExerciseMachine> ExerciseMachines
		{
			get
			{
				return this.GetTable<ExerciseMachine>();
			}
		}
		
		public System.Data.Linq.Table<Facility> Facilities
		{
			get
			{
				return this.GetTable<Facility>();
			}
		}
		
		public System.Data.Linq.Table<TargetBodyPart> TargetBodyParts
		{
			get
			{
				return this.GetTable<TargetBodyPart>();
			}
		}
		
		public System.Data.Linq.Table<User> Users
		{
			get
			{
				return this.GetTable<User>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.insertUsers")]
		public int insertUsers([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Users", DbType="VarChar(255)")] string users, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Password", DbType="VarChar(255)")] string password)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), users, password);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Login")]
		public int Login([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Username", DbType="VarChar(255)")] string username)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), username);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.insertactivity")]
		public int insertactivity([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> userid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> facilityid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> exercisemachineid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> reps, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> weights, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> time, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(MAX)")] string other, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> sets)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userid, facilityid, exercisemachineid, reps, weights, time, other, sets);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Activity")]
	public partial class Activity : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.DateTime _Date;
		
		private System.Nullable<int> _UserID;
		
		private System.Nullable<int> _FacilityID;
		
		private System.Nullable<int> _ExerciseMachineID;
		
		private System.Nullable<int> _Reps;
		
		private System.Nullable<int> _Weights;
		
		private System.Nullable<int> _Time;
		
		private string _Other;
		
		private System.Nullable<int> _Sets;
		
		private EntityRef<ExerciseMachine> _ExerciseMachine;
		
		private EntityRef<Facility> _Facility;
		
		private EntityRef<User> _User;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnDateChanging(System.DateTime value);
    partial void OnDateChanged();
    partial void OnUserIDChanging(System.Nullable<int> value);
    partial void OnUserIDChanged();
    partial void OnFacilityIDChanging(System.Nullable<int> value);
    partial void OnFacilityIDChanged();
    partial void OnExerciseMachineIDChanging(System.Nullable<int> value);
    partial void OnExerciseMachineIDChanged();
    partial void OnRepsChanging(System.Nullable<int> value);
    partial void OnRepsChanged();
    partial void OnWeightsChanging(System.Nullable<int> value);
    partial void OnWeightsChanged();
    partial void OnTimeChanging(System.Nullable<int> value);
    partial void OnTimeChanged();
    partial void OnOtherChanging(string value);
    partial void OnOtherChanged();
    partial void OnSetsChanging(System.Nullable<int> value);
    partial void OnSetsChanged();
    #endregion
		
		public Activity()
		{
			this._ExerciseMachine = default(EntityRef<ExerciseMachine>);
			this._Facility = default(EntityRef<Facility>);
			this._User = default(EntityRef<User>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="DateTime NOT NULL")]
		public System.DateTime Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this.OnDateChanging(value);
					this.SendPropertyChanging();
					this._Date = value;
					this.SendPropertyChanged("Date");
					this.OnDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="Int")]
		public System.Nullable<int> UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					if (this._User.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacilityID", DbType="Int")]
		public System.Nullable<int> FacilityID
		{
			get
			{
				return this._FacilityID;
			}
			set
			{
				if ((this._FacilityID != value))
				{
					if (this._Facility.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFacilityIDChanging(value);
					this.SendPropertyChanging();
					this._FacilityID = value;
					this.SendPropertyChanged("FacilityID");
					this.OnFacilityIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExerciseMachineID", DbType="Int")]
		public System.Nullable<int> ExerciseMachineID
		{
			get
			{
				return this._ExerciseMachineID;
			}
			set
			{
				if ((this._ExerciseMachineID != value))
				{
					if (this._ExerciseMachine.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnExerciseMachineIDChanging(value);
					this.SendPropertyChanging();
					this._ExerciseMachineID = value;
					this.SendPropertyChanged("ExerciseMachineID");
					this.OnExerciseMachineIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reps", DbType="Int")]
		public System.Nullable<int> Reps
		{
			get
			{
				return this._Reps;
			}
			set
			{
				if ((this._Reps != value))
				{
					this.OnRepsChanging(value);
					this.SendPropertyChanging();
					this._Reps = value;
					this.SendPropertyChanged("Reps");
					this.OnRepsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weights", DbType="Int")]
		public System.Nullable<int> Weights
		{
			get
			{
				return this._Weights;
			}
			set
			{
				if ((this._Weights != value))
				{
					this.OnWeightsChanging(value);
					this.SendPropertyChanging();
					this._Weights = value;
					this.SendPropertyChanged("Weights");
					this.OnWeightsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Time", DbType="Int")]
		public System.Nullable<int> Time
		{
			get
			{
				return this._Time;
			}
			set
			{
				if ((this._Time != value))
				{
					this.OnTimeChanging(value);
					this.SendPropertyChanging();
					this._Time = value;
					this.SendPropertyChanged("Time");
					this.OnTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Other", DbType="VarChar(MAX)")]
		public string Other
		{
			get
			{
				return this._Other;
			}
			set
			{
				if ((this._Other != value))
				{
					this.OnOtherChanging(value);
					this.SendPropertyChanging();
					this._Other = value;
					this.SendPropertyChanged("Other");
					this.OnOtherChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sets", DbType="Int")]
		public System.Nullable<int> Sets
		{
			get
			{
				return this._Sets;
			}
			set
			{
				if ((this._Sets != value))
				{
					this.OnSetsChanging(value);
					this.SendPropertyChanging();
					this._Sets = value;
					this.SendPropertyChanged("Sets");
					this.OnSetsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ExerciseMachine_Activity", Storage="_ExerciseMachine", ThisKey="ExerciseMachineID", OtherKey="ID", IsForeignKey=true)]
		public ExerciseMachine ExerciseMachine
		{
			get
			{
				return this._ExerciseMachine.Entity;
			}
			set
			{
				ExerciseMachine previousValue = this._ExerciseMachine.Entity;
				if (((previousValue != value) 
							|| (this._ExerciseMachine.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ExerciseMachine.Entity = null;
						previousValue.Activities.Remove(this);
					}
					this._ExerciseMachine.Entity = value;
					if ((value != null))
					{
						value.Activities.Add(this);
						this._ExerciseMachineID = value.ID;
					}
					else
					{
						this._ExerciseMachineID = default(Nullable<int>);
					}
					this.SendPropertyChanged("ExerciseMachine");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Facility_Activity", Storage="_Facility", ThisKey="FacilityID", OtherKey="ID", IsForeignKey=true)]
		public Facility Facility
		{
			get
			{
				return this._Facility.Entity;
			}
			set
			{
				Facility previousValue = this._Facility.Entity;
				if (((previousValue != value) 
							|| (this._Facility.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Facility.Entity = null;
						previousValue.Activities.Remove(this);
					}
					this._Facility.Entity = value;
					if ((value != null))
					{
						value.Activities.Add(this);
						this._FacilityID = value.ID;
					}
					else
					{
						this._FacilityID = default(Nullable<int>);
					}
					this.SendPropertyChanged("Facility");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_Activity", Storage="_User", ThisKey="UserID", OtherKey="ID", IsForeignKey=true)]
		public User User
		{
			get
			{
				return this._User.Entity;
			}
			set
			{
				User previousValue = this._User.Entity;
				if (((previousValue != value) 
							|| (this._User.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._User.Entity = null;
						previousValue.Activities.Remove(this);
					}
					this._User.Entity = value;
					if ((value != null))
					{
						value.Activities.Add(this);
						this._UserID = value.ID;
					}
					else
					{
						this._UserID = default(Nullable<int>);
					}
					this.SendPropertyChanged("User");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BodyHalf")]
	public partial class BodyHalf : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Value;
		
		private EntitySet<TargetBodyPart> _TargetBodyParts;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnValueChanging(string value);
    partial void OnValueChanged();
    #endregion
		
		public BodyHalf()
		{
			this._TargetBodyParts = new EntitySet<TargetBodyPart>(new Action<TargetBodyPart>(this.attach_TargetBodyParts), new Action<TargetBodyPart>(this.detach_TargetBodyParts));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Value", DbType="VarChar(25)")]
		public string Value
		{
			get
			{
				return this._Value;
			}
			set
			{
				if ((this._Value != value))
				{
					this.OnValueChanging(value);
					this.SendPropertyChanging();
					this._Value = value;
					this.SendPropertyChanged("Value");
					this.OnValueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BodyHalf_TargetBodyPart", Storage="_TargetBodyParts", ThisKey="ID", OtherKey="BodyHalfID")]
		public EntitySet<TargetBodyPart> TargetBodyParts
		{
			get
			{
				return this._TargetBodyParts;
			}
			set
			{
				this._TargetBodyParts.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TargetBodyParts(TargetBodyPart entity)
		{
			this.SendPropertyChanging();
			entity.BodyHalf = this;
		}
		
		private void detach_TargetBodyParts(TargetBodyPart entity)
		{
			this.SendPropertyChanging();
			entity.BodyHalf = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ExerciseCategorys")]
	public partial class ExerciseCategory : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Type;
		
		private System.Nullable<int> _ExerciseEquipmentCategory;
		
		private EntitySet<ExerciseMachine> _ExerciseMachines;
		
		private EntityRef<ExerciseEquipmentCategory> _ExerciseEquipmentCategory1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnTypeChanging(string value);
    partial void OnTypeChanged();
    partial void OnExerciseEquipmentCategoryChanging(System.Nullable<int> value);
    partial void OnExerciseEquipmentCategoryChanged();
    #endregion
		
		public ExerciseCategory()
		{
			this._ExerciseMachines = new EntitySet<ExerciseMachine>(new Action<ExerciseMachine>(this.attach_ExerciseMachines), new Action<ExerciseMachine>(this.detach_ExerciseMachines));
			this._ExerciseEquipmentCategory1 = default(EntityRef<ExerciseEquipmentCategory>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="VarChar(255)")]
		public string Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this.OnTypeChanging(value);
					this.SendPropertyChanging();
					this._Type = value;
					this.SendPropertyChanged("Type");
					this.OnTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExerciseEquipmentCategory", DbType="Int")]
		public System.Nullable<int> ExerciseEquipmentCategory
		{
			get
			{
				return this._ExerciseEquipmentCategory;
			}
			set
			{
				if ((this._ExerciseEquipmentCategory != value))
				{
					if (this._ExerciseEquipmentCategory1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnExerciseEquipmentCategoryChanging(value);
					this.SendPropertyChanging();
					this._ExerciseEquipmentCategory = value;
					this.SendPropertyChanged("ExerciseEquipmentCategory");
					this.OnExerciseEquipmentCategoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ExerciseCategory_ExerciseMachine", Storage="_ExerciseMachines", ThisKey="ID", OtherKey="ExerciseCategoryID")]
		public EntitySet<ExerciseMachine> ExerciseMachines
		{
			get
			{
				return this._ExerciseMachines;
			}
			set
			{
				this._ExerciseMachines.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ExerciseEquipmentCategory_ExerciseCategory", Storage="_ExerciseEquipmentCategory1", ThisKey="ExerciseEquipmentCategory", OtherKey="ID", IsForeignKey=true)]
		public ExerciseEquipmentCategory ExerciseEquipmentCategory1
		{
			get
			{
				return this._ExerciseEquipmentCategory1.Entity;
			}
			set
			{
				ExerciseEquipmentCategory previousValue = this._ExerciseEquipmentCategory1.Entity;
				if (((previousValue != value) 
							|| (this._ExerciseEquipmentCategory1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ExerciseEquipmentCategory1.Entity = null;
						previousValue.ExerciseCategories.Remove(this);
					}
					this._ExerciseEquipmentCategory1.Entity = value;
					if ((value != null))
					{
						value.ExerciseCategories.Add(this);
						this._ExerciseEquipmentCategory = value.ID;
					}
					else
					{
						this._ExerciseEquipmentCategory = default(Nullable<int>);
					}
					this.SendPropertyChanged("ExerciseEquipmentCategory1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ExerciseMachines(ExerciseMachine entity)
		{
			this.SendPropertyChanging();
			entity.ExerciseCategory = this;
		}
		
		private void detach_ExerciseMachines(ExerciseMachine entity)
		{
			this.SendPropertyChanging();
			entity.ExerciseCategory = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ExerciseEquipmentCategory")]
	public partial class ExerciseEquipmentCategory : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Value;
		
		private EntitySet<ExerciseCategory> _ExerciseCategories;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnValueChanging(string value);
    partial void OnValueChanged();
    #endregion
		
		public ExerciseEquipmentCategory()
		{
			this._ExerciseCategories = new EntitySet<ExerciseCategory>(new Action<ExerciseCategory>(this.attach_ExerciseCategories), new Action<ExerciseCategory>(this.detach_ExerciseCategories));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Value", DbType="VarChar(255)")]
		public string Value
		{
			get
			{
				return this._Value;
			}
			set
			{
				if ((this._Value != value))
				{
					this.OnValueChanging(value);
					this.SendPropertyChanging();
					this._Value = value;
					this.SendPropertyChanged("Value");
					this.OnValueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ExerciseEquipmentCategory_ExerciseCategory", Storage="_ExerciseCategories", ThisKey="ID", OtherKey="ExerciseEquipmentCategory")]
		public EntitySet<ExerciseCategory> ExerciseCategories
		{
			get
			{
				return this._ExerciseCategories;
			}
			set
			{
				this._ExerciseCategories.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ExerciseCategories(ExerciseCategory entity)
		{
			this.SendPropertyChanging();
			entity.ExerciseEquipmentCategory1 = this;
		}
		
		private void detach_ExerciseCategories(ExerciseCategory entity)
		{
			this.SendPropertyChanging();
			entity.ExerciseEquipmentCategory1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ExerciseMachines")]
	public partial class ExerciseMachine : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _ExerciseCategoryID;
		
		private string _Type;
		
		private System.Nullable<int> _TargetBodyPartID;
		
		private EntitySet<Activity> _Activities;
		
		private EntityRef<ExerciseCategory> _ExerciseCategory;
		
		private EntityRef<TargetBodyPart> _TargetBodyPart;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnExerciseCategoryIDChanging(System.Nullable<int> value);
    partial void OnExerciseCategoryIDChanged();
    partial void OnTypeChanging(string value);
    partial void OnTypeChanged();
    partial void OnTargetBodyPartIDChanging(System.Nullable<int> value);
    partial void OnTargetBodyPartIDChanged();
    #endregion
		
		public ExerciseMachine()
		{
			this._Activities = new EntitySet<Activity>(new Action<Activity>(this.attach_Activities), new Action<Activity>(this.detach_Activities));
			this._ExerciseCategory = default(EntityRef<ExerciseCategory>);
			this._TargetBodyPart = default(EntityRef<TargetBodyPart>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExerciseCategoryID", DbType="Int")]
		public System.Nullable<int> ExerciseCategoryID
		{
			get
			{
				return this._ExerciseCategoryID;
			}
			set
			{
				if ((this._ExerciseCategoryID != value))
				{
					if (this._ExerciseCategory.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnExerciseCategoryIDChanging(value);
					this.SendPropertyChanging();
					this._ExerciseCategoryID = value;
					this.SendPropertyChanged("ExerciseCategoryID");
					this.OnExerciseCategoryIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="VarChar(255)")]
		public string Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this.OnTypeChanging(value);
					this.SendPropertyChanging();
					this._Type = value;
					this.SendPropertyChanged("Type");
					this.OnTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TargetBodyPartID", DbType="Int")]
		public System.Nullable<int> TargetBodyPartID
		{
			get
			{
				return this._TargetBodyPartID;
			}
			set
			{
				if ((this._TargetBodyPartID != value))
				{
					if (this._TargetBodyPart.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTargetBodyPartIDChanging(value);
					this.SendPropertyChanging();
					this._TargetBodyPartID = value;
					this.SendPropertyChanged("TargetBodyPartID");
					this.OnTargetBodyPartIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ExerciseMachine_Activity", Storage="_Activities", ThisKey="ID", OtherKey="ExerciseMachineID")]
		public EntitySet<Activity> Activities
		{
			get
			{
				return this._Activities;
			}
			set
			{
				this._Activities.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ExerciseCategory_ExerciseMachine", Storage="_ExerciseCategory", ThisKey="ExerciseCategoryID", OtherKey="ID", IsForeignKey=true)]
		public ExerciseCategory ExerciseCategory
		{
			get
			{
				return this._ExerciseCategory.Entity;
			}
			set
			{
				ExerciseCategory previousValue = this._ExerciseCategory.Entity;
				if (((previousValue != value) 
							|| (this._ExerciseCategory.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ExerciseCategory.Entity = null;
						previousValue.ExerciseMachines.Remove(this);
					}
					this._ExerciseCategory.Entity = value;
					if ((value != null))
					{
						value.ExerciseMachines.Add(this);
						this._ExerciseCategoryID = value.ID;
					}
					else
					{
						this._ExerciseCategoryID = default(Nullable<int>);
					}
					this.SendPropertyChanged("ExerciseCategory");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TargetBodyPart_ExerciseMachine", Storage="_TargetBodyPart", ThisKey="TargetBodyPartID", OtherKey="ID", IsForeignKey=true)]
		public TargetBodyPart TargetBodyPart
		{
			get
			{
				return this._TargetBodyPart.Entity;
			}
			set
			{
				TargetBodyPart previousValue = this._TargetBodyPart.Entity;
				if (((previousValue != value) 
							|| (this._TargetBodyPart.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TargetBodyPart.Entity = null;
						previousValue.ExerciseMachines.Remove(this);
					}
					this._TargetBodyPart.Entity = value;
					if ((value != null))
					{
						value.ExerciseMachines.Add(this);
						this._TargetBodyPartID = value.ID;
					}
					else
					{
						this._TargetBodyPartID = default(Nullable<int>);
					}
					this.SendPropertyChanged("TargetBodyPart");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Activities(Activity entity)
		{
			this.SendPropertyChanging();
			entity.ExerciseMachine = this;
		}
		
		private void detach_Activities(Activity entity)
		{
			this.SendPropertyChanging();
			entity.ExerciseMachine = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Facility")]
	public partial class Facility : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Name;
		
		private System.Nullable<float> _Lat;
		
		private System.Nullable<float> _Long;
		
		private EntitySet<Activity> _Activities;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnLatChanging(System.Nullable<float> value);
    partial void OnLatChanged();
    partial void OnLongChanging(System.Nullable<float> value);
    partial void OnLongChanged();
    #endregion
		
		public Facility()
		{
			this._Activities = new EntitySet<Activity>(new Action<Activity>(this.attach_Activities), new Action<Activity>(this.detach_Activities));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(255)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lat", DbType="Real")]
		public System.Nullable<float> Lat
		{
			get
			{
				return this._Lat;
			}
			set
			{
				if ((this._Lat != value))
				{
					this.OnLatChanging(value);
					this.SendPropertyChanging();
					this._Lat = value;
					this.SendPropertyChanged("Lat");
					this.OnLatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Long", DbType="Real")]
		public System.Nullable<float> Long
		{
			get
			{
				return this._Long;
			}
			set
			{
				if ((this._Long != value))
				{
					this.OnLongChanging(value);
					this.SendPropertyChanging();
					this._Long = value;
					this.SendPropertyChanged("Long");
					this.OnLongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Facility_Activity", Storage="_Activities", ThisKey="ID", OtherKey="FacilityID")]
		public EntitySet<Activity> Activities
		{
			get
			{
				return this._Activities;
			}
			set
			{
				this._Activities.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Activities(Activity entity)
		{
			this.SendPropertyChanging();
			entity.Facility = this;
		}
		
		private void detach_Activities(Activity entity)
		{
			this.SendPropertyChanging();
			entity.Facility = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TargetBodyPart")]
	public partial class TargetBodyPart : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _BodyHalfID;
		
		private string _Value;
		
		private EntitySet<ExerciseMachine> _ExerciseMachines;
		
		private EntityRef<BodyHalf> _BodyHalf;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnBodyHalfIDChanging(System.Nullable<int> value);
    partial void OnBodyHalfIDChanged();
    partial void OnValueChanging(string value);
    partial void OnValueChanged();
    #endregion
		
		public TargetBodyPart()
		{
			this._ExerciseMachines = new EntitySet<ExerciseMachine>(new Action<ExerciseMachine>(this.attach_ExerciseMachines), new Action<ExerciseMachine>(this.detach_ExerciseMachines));
			this._BodyHalf = default(EntityRef<BodyHalf>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BodyHalfID", DbType="Int")]
		public System.Nullable<int> BodyHalfID
		{
			get
			{
				return this._BodyHalfID;
			}
			set
			{
				if ((this._BodyHalfID != value))
				{
					if (this._BodyHalf.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnBodyHalfIDChanging(value);
					this.SendPropertyChanging();
					this._BodyHalfID = value;
					this.SendPropertyChanged("BodyHalfID");
					this.OnBodyHalfIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Value", DbType="VarChar(255)")]
		public string Value
		{
			get
			{
				return this._Value;
			}
			set
			{
				if ((this._Value != value))
				{
					this.OnValueChanging(value);
					this.SendPropertyChanging();
					this._Value = value;
					this.SendPropertyChanged("Value");
					this.OnValueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TargetBodyPart_ExerciseMachine", Storage="_ExerciseMachines", ThisKey="ID", OtherKey="TargetBodyPartID")]
		public EntitySet<ExerciseMachine> ExerciseMachines
		{
			get
			{
				return this._ExerciseMachines;
			}
			set
			{
				this._ExerciseMachines.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BodyHalf_TargetBodyPart", Storage="_BodyHalf", ThisKey="BodyHalfID", OtherKey="ID", IsForeignKey=true)]
		public BodyHalf BodyHalf
		{
			get
			{
				return this._BodyHalf.Entity;
			}
			set
			{
				BodyHalf previousValue = this._BodyHalf.Entity;
				if (((previousValue != value) 
							|| (this._BodyHalf.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._BodyHalf.Entity = null;
						previousValue.TargetBodyParts.Remove(this);
					}
					this._BodyHalf.Entity = value;
					if ((value != null))
					{
						value.TargetBodyParts.Add(this);
						this._BodyHalfID = value.ID;
					}
					else
					{
						this._BodyHalfID = default(Nullable<int>);
					}
					this.SendPropertyChanged("BodyHalf");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ExerciseMachines(ExerciseMachine entity)
		{
			this.SendPropertyChanging();
			entity.TargetBodyPart = this;
		}
		
		private void detach_ExerciseMachines(ExerciseMachine entity)
		{
			this.SendPropertyChanging();
			entity.TargetBodyPart = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Users")]
	public partial class User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Username;
		
		private string _Password;
		
		private EntitySet<Activity> _Activities;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    #endregion
		
		public User()
		{
			this._Activities = new EntitySet<Activity>(new Action<Activity>(this.attach_Activities), new Action<Activity>(this.detach_Activities));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="VarChar(255)")]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(255)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_Activity", Storage="_Activities", ThisKey="ID", OtherKey="UserID")]
		public EntitySet<Activity> Activities
		{
			get
			{
				return this._Activities;
			}
			set
			{
				this._Activities.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Activities(Activity entity)
		{
			this.SendPropertyChanging();
			entity.User = this;
		}
		
		private void detach_Activities(Activity entity)
		{
			this.SendPropertyChanging();
			entity.User = null;
		}
	}
}
#pragma warning restore 1591
